version: '3.8'

services:
  # Base de Datos VENTAS 
  tienda-db-cdci:
    image: mysql:8.0
    container_name: tienda-db-cdci
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: tienda_ventas_db
    networks:
      - innovatech-net
    volumes:
      - db_ventas_persistente:/var/lib/mysql # REQUERIMIENTO IE3: Persistencia de Ventas
    restart: always

  # Base de Datos DESPACHOS 
  tienda-db-despachos:
    image: mysql:8.0
    container_name: tienda-db-despachos
    ports:
      - "3307:3306" # Puerto 3307 en AWS redireccionado al puerto interno 3306 de MySQL
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: tienda_despachos_db
    networks:
      - innovatech-net
    volumes:
      - db_despachos_persistente:/var/lib/mysql # REQUERIMIENTO IE3: Persistencia de Despachos
    restart: always

  # Microservicio de Ventas
  back-ventas:
    build: ./backend-ventas
    container_name: back-ventas-container
    ports:
      - "8080:8080" # Tu puerto estándar de Ventas en AWS
    networks:
      - innovatech-net
    depends_on:
      - tienda-db-cdci
    environment:
      # Inyectamos de forma separada las variables exactas que tu código espera leer
      - DB_ENDPOINT=tienda-db-cdci
      - DB_PORT=3306
      - DB_NAME=tienda_ventas_db
      - DB_USERNAME=root
      - DB_PASSWORD=root_password
    restart: always

  # Microservicio de Despachos
  back-despachos:
    build: ./backend-despachos
    container_name: back-despachos-container
    ports:
      - "8082:8081" # Puerto 8082 en AWS redireccionado al puerto interno 8081
    networks:
      - innovatech-net
    depends_on:
      - tienda-db-despachos
    environment:
      # Inyectamos de forma separada las variables exactas que tu código espera leer
      - DB_ENDPOINT=tienda-db-despachos
      - DB_PORT=3306
      - DB_NAME=tienda_despachos_db
      - DB_USERNAME=root
      - DB_PASSWORD=root_password
    restart: always

  # Frontend del Sistema
  front-despacho:
    build: ./frontend
    container_name: front-despacho-container
    ports:
      - "80:80" # Accesible públicamente por el puerto HTTP estándar
    depends_on:
      - back-ventas
      - back-despachos
    networks:
      - innovatech-net
    restart: always

networks:
  innovatech-net:
    driver: bridge

volumes:
  db_ventas_persistente:
  db_despachos_persistente: