services:
  # Base de Datos (Requerimiento 2 y 4)
  db-datos:
    image: postgres:15-alpine
    container_name: db-innovatech
    environment:
      POSTGRES_DB: innovatech_db
      POSTGRES_PASSWORD: admin_password
    networks:
      - innovatech-net
    volumes:
      - db_persistente:/var/lib/postgresql/data # Persistencia crítica
    restart: always

  back-ventas:
    build: ./back-Ventas_SpringBoot
    container_name: back-ventas-container
    ports:
      - "8081:8080" # Mapeo para acceso externo/front
    networks:
      - innovatech-net
    depends_on:
      - db-datos
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-datos:5432/innovatech_db
    restart: always

  back-despachos:
    build: ./back-Despachos_SpringBoot
    container_name: back-despachos-container
    ports:
      - "8080:8080" # Mapeo para acceso externo/front
    networks:
      - innovatech-net
    depends_on:
      - db-datos
    volumes:
      - despachos_data:/app/data # Persistencia de archivos/logs
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-datos:5432/innovatech_db
    restart: always

  front-despacho:
    build: ./front_despacho
    container_name: front-despacho-container
    ports:
      - "80:80" 
    depends_on:
      - back-ventas
      - back-despachos
    networks:
      - innovatech-net
    restart: always

networks:
  innovatech-net:
    driver: bridge

volumes:
  despachos_data:
  db_persistente: # Volumen para que la BD no pierda los datos