spring.application.name=Springboot-API-REST

# Configuración de la base de datos con valores por defecto para que no falle en GitHub Actions
spring.datasource.url=jdbc:mysql://${DB_ENDPOINT:localhost}:${DB_PORT:3306}/${DB_NAME:tienda_perritos}?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root_password}
spring.datasource.platform=mysql

# Configuración de Hibernate
spring.jpa.database=mysql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

springdoc.swagger-ui.path=/swagger-ui.html